name: Build Test

# On push to main, when one of the following labels exists: `patch`, `minor`, `major`
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, "patch") || contains(github.event.pull_request.labels.*.name, "minor") || contains(github.event.pull_request.labels.*.name, "major") }}
    name: Build Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install Dependencies
        run: npm install
      - name: Build Extension
        run: npm run vsce -- ls
