name: Deploy

on:
  release:
    types:
      - created

env:
  # Specific name is required to login: https://code.visualstudio.com/api/working-with-extensions/continuous-integration
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  build:
    if: startsWith( github.ref, 'refs/tags/releases/')
    name: Publish Extension from Release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Publish
        run: npm run deploy
