name: Deploy

on:
  release:
    types: [released]

env:
  # Specific name is required to login: https://code.visualstudio.com/api/working-with-extensions/continuous-integration
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  build:
    name: Publish Extension from Release
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

      - name: Publish
        run: npm run deploy
