name: Deploy

on:
  push:
    branches:
      - main
    labels:
      - patch
      - minor
      - major

env:
  # Specific name is required to login: https://code.visualstudio.com/api/working-with-extensions/continuous-integration
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  build:
    name: Build and Publish Extension
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        version-labels: [patch, minor, major]

    steps:
      - name: Install Dependencies
        run: npm install
      - name: Build Extension
        run: npm run pack -- ${{ github.event.pull_request.labels.find(label => [${{version-labels}}].includes(label.name)).name }} -m "build %s [skip ci]"

      - name: Publish
        run: npm run deploy
